hack(hal): add in 8 more fake felix links, since the user logic crashes with only 2 stations
It generates an error:

ERROR: [Synth 8-97] array index 2 out of range [/UserLogic/ucm/src/ucm_cvp.vhd:327]

It seems like the # of stations is hardcoded all over the place